[package]
name = "vidya-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.6", features=["dynamic"] }
tiled = { git = "https://github.com/mapeditor/rs-tiled", branch = "master" }  # Temporary until 1.0 release
anyhow = "1.0"
log = "0.4"
