[package]
name = "vidya-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.6" }
tiled = { git = "https://github.com/Anti-Alias/tiled-rs", branch = "add-group-layer" }  # Temporary until group layers are supported
anyhow = "1.0"
log = "0.4"